./if_id.v 
./id.v 
./regfile.v 
./id_ex.v 
./ex.v 
./ex_mem.v 
./mem.v 
./mem_wb.v  
./hilo_reg.v  
./ctrl.v  
./div.v   
./LLbit_reg.v
./pc_reg.v
./inst_rom.v 
./data_ram.v 
./openmips.v  
./openmips_min_sopc.v  
./openmips_min_sopc_tb.v